Ext.define('MBilling.model.QueueMember', {
    extend: 'Ext.data.Model',
    idProperty: 'id',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'uniqueid',
        type: 'int'
    }, {
        name: 'id_user',
        type: 'int'
    }, {
        name: 'membername',
        type: 'string'
    }, {
        name: 'queue_name',
        type: 'string'
    }, {
        name: 'interface',
        type: 'string'
    }, {
        name: 'penalty',
        type: 'int'
    }, {
        name: 'paused',
        type: 'int'
    }, 'idUserusername'],
    proxy: {
        type: 'uxproxy',
        module: 'queueMember'
    }
});