Ext.define('MBilling.model.QueueMemberDashBoard', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'agentName',
        type: 'string'
    }, {
        name: 'number',
        type: 'string'
    }, {
        name: 'totalCalls',
        type: 'string'
    }, {
        name: 'last_call',
        type: 'string'
    }, {
        name: 'agentId',
        type: 'string'
    }, {
        name: 'agentStatus',
        type: 'string'
    }, {
        name: 'score',
        type: 'string'
    }, 'idQueuename'],
    proxy: {
        type: 'uxproxy',
        module: 'queueMemberDashBoard'
    }
});