Ext.define('MBilling.model.Rate', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'id_plan',
        type: 'int'
    }, {
        name: 'id_trunk_group',
        type: 'int'
    }, {
        name: 'id_prefix',
        type: 'int'
    }, {
        name: 'rateinitial',
        type: 'number'
    }, {
        name: 'initblock',
        type: 'int'
    }, {
        name: 'billingblock',
        type: 'int'
    }, {
        name: 'connectcharge',
        type: 'number'
    }, {
        name: 'disconnectcharge',
        type: 'number'
    }, {
        name: 'additional_grace',
        type: 'string'
    }, {
        name: 'minimal_cost',
        type: 'int'
    }, {
        name: 'minimal_time_charge',
        type: 'int'
    }, {
        name: 'package_offer',
        type: 'int'
    }, {
        name: 'status',
        type: 'int'
    }, 'idPrefixdestination', 'idPrefixprefix', 'idTrunkGroupname', 'idPlanname'],
    proxy: {
        type: 'uxproxy',
        module: 'rate'
    }
});