Ext.define('MBilling.model.SendCreditProducts', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'country_code',
        type: 'int'
    }, {
        name: 'operator_id',
        type: 'string'
    }, {
        name: 'SkuCode',
        type: 'string'
    }, {
        name: 'country',
        type: 'string'
    }, {
        name: 'operator_name',
        type: 'string'
    }, {
        name: 'currency_dest',
        type: 'string'
    }, {
        name: 'product',
        type: 'string'
    }, {
        name: 'currency_orig',
        type: 'string'
    }, {
        name: 'wholesale_price',
        type: 'string'
    }, {
        name: 'send_value',
        type: 'string'
    }, {
        name: 'provider',
        type: 'string'
    }, {
        name: 'info',
        type: 'string'
    }, {
        name: 'status',
        type: 'int'
    }, {
        name: 'retail_price',
        type: 'string'
    }, 'idUserusername'],
    proxy: {
        type: 'uxproxy',
        module: 'sendCreditProducts'
    }
});