Ext.define('MBilling.model.SendCreditSummary', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'day',
        type: 'date',
        dateFormat: 'Y-m-d'
    }, {
        name: 'id_user',
        type: 'int'
    }, {
        name: 'service',
        type: 'string'
    }, {
        name: 'total_sale',
        type: 'string'
    }, {
        name: 'earned',
        type: 'string'
    }, {
        name: 'commision',
        type: 'string'
    }, {
        name: 'profit',
        type: 'string'
    }, 'idUserusername'],
    proxy: {
        type: 'uxproxy',
        module: 'sendCreditSummary'
    }
});