Ext.define('MBilling.model.Servers', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'id',
        type: 'int'
    }, {
        name: 'host',
        type: 'string'
    }, {
        name: 'name',
        type: 'string'
    }, {
        name: 'username',
        type: 'string'
    }, {
        name: 'password',
        type: 'string'
    }, {
        name: 'port',
        type: 'string'
    }, {
        name: 'sip_port',
        type: 'string'
    }, {
        name: 'status',
        type: 'int'
    }, {
        name: 'weight',
        type: 'int'
    }, {
        name: 'description',
        type: 'string'
    }, {
        name: 'type',
        type: 'string'
    }, {
        name: 'public_ip',
        type: 'string'
    }],
    proxy: {
        type: 'uxproxy',
        module: 'servers'
    }
});